import migrations.register_auth_model  # noqa: F401
import app.orgs.models  # noqa: F401
import app.api_auth.models  # noqa: F401
import app.file_upload.models  # noqa: F401
import app.claude_hook.models  # noqa: F401
import app.backboard.models  # noqa: F401
import app.github.models  # noqa: F401
import app.job_queue.models  # noqa: F401
import app.gap_chat.models  # noqa: F401
